language: android
jdk: oraclejdk8
android:
  components:
     - tools
     - platform-tools
     - tools
     - build-tools-25.0.2
     - android-19
     - android-25
     - extra-android-m2repository
     - sys-img-armeabi-v7a-android-19
     - sys-img-armeabi-v7a-android-25
  licenses:
    - 'android-sdk-license-.+'