git:
  submodules: false
dist: trusty
language: android
jdk: oraclejdk8
android:
  components:
     - tools
     - platform-tools
     - tools
     - build-tools-29.0.2
     - android-29
     - extra-android-m2repository
     - sys-img-armeabi-v7a-android-23
  licenses:
    - 'android-sdk-license-.+'
before_script:
  - sudo apt-get -qq update
  - android list targets
  - echo no | android create avd --force -n test -t "android-29" --abi "armeabi-v7a"
  - emulator -avd test -no-audio -no-window &
  - ./android-wait-for-emulator.sh
  - adb shell input keyevent 82 &
script:
    - ./gradlew test
    - ./gradlew connectedAndroidTest
