git:
  submodules: false
dist: trusty
language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_API_LEVEL=24
    - ANDROID_BUILD_TOOLS_VERSION=29.0.2
    - ANDROID_ABI=armeabi-v7a
android:
  components:
     - tools
     - platform-tools
     - tools
     - build-tools-$ANDROID_BUILD_TOOLS_VERSION
     - android-$ANDROID_API_LEVEL
     - extra-android-m2repository
     - sys-img-$ANDROID_ABI-android-$ANDROID_API_LEVEL
  licenses:
    - 'android-sdk-license-.+'
before_script:
  - sudo apt-get -qq update
  - android list targets
  - echo no | android create avd --force -n test -t android-$ANDROID_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
    - ./gradlew test
    - ./gradlew connectedAndroidTest
