version: 2.1
commands:
  clone:
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
jobs:
  unit_test:
    docker:
      - image: cimg/android:2024.01.1
    steps:
      - clone
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies --no-daemon
      - run:
          name: Tests
          command: ./gradlew test --no-daemon
      - store_test_results:
          path: core/unicode/build/test-results
      - store_artifacts:
          path: core/unicode/build/reports
          destination: circleci/reports/unicode
      - store_test_results:
          path: core/database/build/test-results
      - store_artifacts:
          path: core/database/build/reports
          destination: circleci/reports/database
      - store_test_results:
          path: prepopulator/build/test-results
      - store_artifacts:
          path: prepopulator/build/reports
          destination: circleci/reports/prepopulator
      - store_test_results:
          path: android/build/test-results
      - store_artifacts:
          path: android/build/reports
          destination: circleci/reports/android
  build_artifacts:
    docker:
      - image: cimg/android:2024.01.1
    steps:
      - clone
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies --no-daemon
      - run:
          name: Build APK
          command: ./gradlew :android:assembleRelease --no-daemon --max-workers 4
      - store_artifacts:
          path: android/build/outputs/apk/release
          destination: circleci/apk
workflows:
  pull_request:
    jobs:
      - unit_test:
          filters:
            branches:
              ignore:
                - main
  build:
    jobs:
      - unit_test:
          filters:
            branches:
              only:
                - main
      - build_artifacts:
          requires:
            - unit_test
          filters:
            branches:
              only:
                - main
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - unit_test
