version: 2.1
jobs:
  unit_test:
    docker:
      - image: cimg/android:2024.01.1
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies --no-daemon
      - run:
          name: Tests
          command: ./gradlew test --no-daemon
      - store_test_results:
          path: android/build/test-results
      - store_artifacts:
          path: android/build/reports
          destination: circleci/reports
  build_artifacts:
    docker:
      - image: cimg/android:2024.01.1
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies --no-daemon
      - run:
          name: Build APK
          command: ./gradlew :android:assembleRelease --no-daemon --max-workers 4
      - store_artifacts:
          path: android/build/outputs/apk/release
          destination: circleci/apk
workflows:
  pull_request:
    jobs:
      - unit_test:
          filters:
            branches:
              ignore:
                - master
  build:
    jobs:
      - unit_test:
          filters:
            branches:
              only:
                - master
      - build_artifacts:
          requires:
            - unit_test
          filters:
            branches:
              only:
                - master
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - unit_test
