version: 2.1
jobs:
  unit_test:
    docker:
      - image: circleci/android:api-29
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: circleci/reports
      - store_test_results:
          path: app/build/test-results
workflows:
  pull_request:
    jobs:
      - unit_test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - unit_test